app = "diamond-trading-bot-fly"

[env]
  PORT = "8000"
  PYTHON_VERSION = "3.11.0"

[http_service]
  internal_port = 8000
  force_https = true
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"
